#!/usr/bin/env bash
#
# ARS Plugin Builder — Linux installer.
#
# No root, XDG-compliant, re-runnable (run again to upgrade). Builds the
# runnable jar if needed, installs it under ~/.local, and registers a desktop
# launcher + icon so "ARS Plugin Builder" shows up in your application menu.
#
# Assumes Java 21+ on PATH (and Maven, only if the jar still needs building).
# Per the suite's policy it DETECTS those and advises — it never installs them.
#
# Usage:
#   ./install.sh              build (if needed) + install / upgrade
#   ./install.sh --uninstall  remove everything this script installed
#
set -euo pipefail

APP_ID="ars-plugin-builder"
APP_NAME="ARS Plugin Builder"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
BIN_DIR="$HOME/.local/bin"
APP_DIR="$DATA_HOME/$APP_ID"
APPS_DIR="$DATA_HOME/applications"
ICON_DIR="$DATA_HOME/icons/hicolor/scalable/apps"
LAUNCHER="$BIN_DIR/$APP_ID"
DESKTOP="$APPS_DIR/$APP_ID.desktop"
ICON="$ICON_DIR/$APP_ID.svg"
JAR_INSTALLED="$APP_DIR/$APP_ID.jar"

refresh_caches() {
    command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$APPS_DIR" 2>/dev/null || true
    command -v gtk-update-icon-cache  >/dev/null 2>&1 && gtk-update-icon-cache -q -t "$DATA_HOME/icons/hicolor" 2>/dev/null || true
}

uninstall() {
    echo "Removing $APP_NAME…"
    rm -f "$LAUNCHER" "$DESKTOP" "$ICON" "$JAR_INSTALLED"
    rmdir "$APP_DIR" 2>/dev/null || true
    refresh_caches
    echo "Done. (Your plugins in ~/.j-log are left untouched.)"
}

if [[ "${1:-}" == "--uninstall" || "${1:-}" == "-u" ]]; then
    uninstall
    exit 0
fi

# --- Java: detect + advise (never auto-install) ---
command -v java >/dev/null 2>&1 || {
    echo "error: Java 21+ is required but 'java' was not found on PATH."
    echo "       Install a JDK 21 (e.g. 'sudo apt install openjdk-21-jdk'), then re-run."
    exit 1
}
JV="$(java -version 2>&1 | head -1 | sed -E 's/.*version "([0-9]+).*/\1/')"
if [[ "$JV" =~ ^[0-9]+$ ]] && (( JV < 21 )); then
    echo "error: Java 21+ is required; found Java $JV. Install a JDK 21 and re-run."
    exit 1
fi

# --- Resolve the runnable jar, building it if absent ---
find_jar() {
    ls -t "$SCRIPT_DIR"/target/$APP_ID-*.jar 2>/dev/null \
        | grep -Ev -- '-(sources|javadoc)\.jar$' | head -n1 || true
}
JAR="$(find_jar)"
if [[ -z "$JAR" ]]; then
    echo "[build] runnable jar not found — building with Maven…"
    command -v mvn >/dev/null 2>&1 || {
        echo "error: Maven is required to build the jar but 'mvn' was not found."
        echo "       Install Maven (and build j-log-engine first), then re-run."
        exit 1
    }
    mvn -q -DskipTests -f "$SCRIPT_DIR/pom.xml" clean package
    JAR="$(find_jar)"
fi
[[ -n "$JAR" ]] || { echo "error: build produced no runnable jar under target/."; exit 1; }

# --- Install files ---
mkdir -p "$APP_DIR" "$BIN_DIR" "$APPS_DIR" "$ICON_DIR"
install -m 644 "$JAR" "$JAR_INSTALLED"
[[ -f "$SCRIPT_DIR/packaging/$APP_ID.svg" ]] && install -m 644 "$SCRIPT_DIR/packaging/$APP_ID.svg" "$ICON"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Launch ARS Plugin Builder (generated by install.sh).
exec java -jar "$JAR_INSTALLED" "\$@"
EOF
chmod +x "$LAUNCHER"

cat > "$DESKTOP" <<EOF
[Desktop Entry]
Type=Application
Name=$APP_NAME
GenericName=Contest & Award Plugin Editor
Comment=Create and edit ARS Suite contest & award plugins with a live score preview
Exec=$LAUNCHER
Icon=$APP_ID
Terminal=false
Categories=Development;HamRadio;
Keywords=ham;amateur radio;contest;cabrillo;adif;plugin;award;ARS;j-log;
StartupNotify=true
EOF

refresh_caches

echo "✓ Installed $APP_NAME ($(basename "$JAR"))"
echo "    jar:      $JAR_INSTALLED"
echo "    launcher: $LAUNCHER"
echo "    desktop:  $DESKTOP"
echo "    icon:     $ICON"
echo
echo "Launch it from your application menu, or run:  $LAUNCHER"
echo "Upgrade later by re-running this script; remove with:  $0 --uninstall"
case ":$PATH:" in
    *":$BIN_DIR:"*) echo "('$APP_ID' is on your PATH — you can just type 'ars-plugin-builder'.)" ;;
    *) echo "Tip: add $BIN_DIR to PATH to run 'ars-plugin-builder' from a terminal." ;;
esac
